//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanBeekRonny_TTI_GPR_d1._1_DM_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beroemdheid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beroemdheid()
        {
            this.FilmBeroemdheden = new HashSet<FilmBeroemdheid>();
        }
    
        public int id { get; set; }
        public string naam { get; set; }
        public string voornaam { get; set; }
        public Nullable<System.DateTime> geboortedatum { get; set; }
        public Nullable<int> nationaliteitId { get; set; }
        public string lengte { get; set; }
        public string handelsmerk { get; set; }
        public Nullable<int> sterrenbeeldId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmBeroemdheid> FilmBeroemdheden { get; set; }
        public virtual Nationaliteit Nationaliteit { get; set; }
        public virtual Sterrenbeeld Sterrenbeeld { get; set; }
    }
}
