//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanBeekRonny_TTI_GPR_d1._1_DM_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.FilmBeroemdheden = new HashSet<FilmBeroemdheid>();
            this.FilmGenres = new HashSet<FilmGenre>();
        }
    
        public int id { get; set; }
        public string titel { get; set; }
        public System.DateTime publicatiedatum { get; set; }
        public string speelduur { get; set; }
        public string verhaallijn { get; set; }
        public Nullable<int> taalId { get; set; }
        public string slogan { get; set; }
        public Nullable<int> leeftijdsgroepId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmBeroemdheid> FilmBeroemdheden { get; set; }
        public virtual Leeftijdsgroep Leeftijdsgroep { get; set; }
        public virtual Taal Taal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmGenre> FilmGenres { get; set; }
    }
}
