//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanBeekRonny_TTI_GPR_d1._1_DM_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sterrenbeeld
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sterrenbeeld()
        {
            this.Beroemdheden = new HashSet<Beroemdheid>();
        }
    
        public int id { get; set; }
        public string sterrebeeld { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beroemdheid> Beroemdheden { get; set; }
    }
}
